auth_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.RegisterFromView.as_view(), name='register'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

knb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth_user/', include('auth_user.urls', namespace="auth_user")),
    url(r'', include('main.urls', namespace="main")),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^lobby/(?P<lobby_id>[0-9]+)/$', views.lobby, name='lobby'),
    url(r'^lobby/create/$', views.create, name='create')
]

auth_user/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class LobbyModel(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User, related_name='owner')
    opponent = models.ForeignKey(User, related_name='opponent', null=True)
    status = models.CharField(max_length=50, default='waiting')

    def __str__(self):
        return self.name

auth_user/views.py
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.contrib.auth import logout


class RegisterFromView(FormView):
    form_class = UserCreationForm
    success_url = '/auth_user/login/'
    template_name = 'auth_user/register.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFromView, self).form_valid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = 'auth_user/login.html'
    success_url = '/'

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)

        return HttpResponseRedirect("/")

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import LobbyModel
# Create your views here.

@login_required()
def index(request):
    username = request.user.username
    user_list = User.objects.all()
    open_lobbies = LobbyModel.objects.filter(status='waiting').exclude(owner=request.user)
    context = {
        'username': username,
        'user_list': user_list,
        'open_lobbies': open_lobbies,
    }
    return render(request, 'main/index.html', context)


@login_required()
def lobby(request, lobby_id):
    l = LobbyModel.objects.get(pk=lobby_id)
    context = {
        'lobby': l,
    }
    if l.owner == request.user:
        return render(request, 'main/lobby.html', context)
    else:
        l.opponent = request.user
        l.status = 'Ready to game'
        l.save()
        return render(request, 'main/lobby.html', context)


@login_required()
def create(request):
    lobby_name = request.POST['lobby_name']
    owner = request.user
    status = 'waiting'

    l = LobbyModel.objects.create(name=lobby_name, owner=owner, status=status)
    l.save()
    return HttpResponseRedirect(reverse('main:lobby', args=(l.id,)))

auth_user/templates/auth_user/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Log in</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Log in</button>
    </form>
    <p> or <a href="{% url 'auth_user:register' %}">Register</a> </p>
  </body>
</html>

auth_user/templates/auth_user/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Join</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Join</button>
    </form>
  </body>
</html>

auth_user/templates/auth_user/test.html
<h1> {{ text }} </h1>

main/templates/main/index.html
<h1> MAIN {{ username }} </h1>

Users - online
<ul>
{% for user in user_list %}
	<li>{{ user.username }}</li>
{% endfor %}
</ul>

Open lobbies
<ul>
{% for lobby in open_lobbies %}
	<li><a href= "{% url 'main:lobby' lobby.id %}">{{ lobby.name }}</a></li>
{% endfor %}
</ul>

<h1>Open Lobby</h1>
<form action="{% url 'main:create' %}" method="post">
	{% csrf_token %}
	<label for="lobby_name">Lobby name</label><br>
	<input type="text" name="lobby_name" id="lobby_name"><br>
	<input type="submit" value="Create">
</form>

main/templates/main/lobby.html
<h1> Battle room - {{lobby.name}} </h1>
<h2> Game master - {{lobby.owner}} </h2>
<h2> Opponent - {{lobby.opponent}}</h2>
<h3> status - {{lobby.status}}</h3>
{% if lobby.status = 'Ready to game' %}
	<button> Start game</button>
{% endif %}